name: Build Erlang

on:
  pull_request:
    branches: ['*']
  push:
    branches: [master]

jobs:
  build:
    name: Build and verify
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install thrift
        uses: valitydev/action-setup-thrift@v0.0.5

      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        id: beam
        with:
          otp-version: '24'
          rebar3-version: '3.18'

      - name: Restore PLT cache
        uses: actions/cache@v2
        id: plt-cache
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            _build/default/rebar3_*_plt

      - run: rebar3 compile
      - run: rebar3 xref
      - run: rebar3 dialyzer
